version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - code-skeptic-network
    environment:
      - REACT_APP_API_URL=http://backend:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - code-skeptic-network
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/code_skeptic
      - JWT_SECRET=your_jwt_secret_here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    volumes:
      - code-skeptic-db-data:/var/lib/postgresql/data
    networks:
      - code-skeptic-network
    environment:
      - POSTGRES_DB=code_skeptic
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d code_skeptic"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  code-skeptic-network:
    driver: bridge

volumes:
  code-skeptic-db-data:

# HUMAN ASSISTANCE NEEDED
# Please review the following:
# 1. Ensure that the frontend and backend Dockerfile paths are correct
# 2. Update the JWT_SECRET with a secure value
# 3. Review and adjust the database credentials as needed
# 4. Confirm that the health check endpoints are correctly implemented in the services